-- =========================================================
-- MenuMaster - Supabase database
-- Run this in Supabase SQL Editor.
-- =========================================================

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
    id bigint generated by default as identity primary key,
    auth_user_id uuid unique references auth.users(id) on delete cascade,
    name text not null,
    username text unique not null,
    email text unique not null,
    phone_number text,
    city text,
    address text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.restaurants (
    id bigint generated by default as identity primary key,
    auth_user_id uuid unique references auth.users(id) on delete cascade,
    name text not null,
    email text unique not null,
    phone_number text,
    description text,
    address text,
    city text,
    image_url text,
    rating numeric(2,1) not null default 0 check (rating >= 0 and rating <= 5),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.menu_items (
    id bigint generated by default as identity primary key,
    restaurant_id bigint not null references public.restaurants(id) on delete cascade,
    name text not null,
    category text not null,
    price numeric(10,2) not null check (price >= 0),
    description text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.reservations (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.profiles(id) on delete cascade,
    restaurant_id bigint not null references public.restaurants(id) on delete cascade,
    people integer not null check (people > 0),
    date date not null,
    time time not null,
    status text not null default 'Pending'
        check (status in ('Pending','Confirmed','Declined','Cancelled')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.reviews (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.profiles(id) on delete cascade,
    restaurant_id bigint not null references public.restaurants(id) on delete cascade,
    rating integer not null check (rating between 1 and 5),
    comment text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(user_id, restaurant_id)
);

create index if not exists idx_profiles_auth_user on public.profiles(auth_user_id);
create index if not exists idx_restaurants_auth_user on public.restaurants(auth_user_id);
create index if not exists idx_restaurants_city on public.restaurants(city);
create index if not exists idx_menu_items_restaurant on public.menu_items(restaurant_id);
create index if not exists idx_reservations_user on public.reservations(user_id);
create index if not exists idx_reservations_restaurant on public.reservations(restaurant_id);
create index if not exists idx_reservations_date on public.reservations(date);
create index if not exists idx_reviews_restaurant on public.reviews(restaurant_id);
create index if not exists idx_reviews_user on public.reviews(user_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists restaurants_updated_at on public.restaurants;
create trigger restaurants_updated_at before update on public.restaurants for each row execute function public.set_updated_at();
drop trigger if exists menu_items_updated_at on public.menu_items;
create trigger menu_items_updated_at before update on public.menu_items for each row execute function public.set_updated_at();
drop trigger if exists reservations_updated_at on public.reservations;
create trigger reservations_updated_at before update on public.reservations for each row execute function public.set_updated_at();
drop trigger if exists reviews_updated_at on public.reviews;
create trigger reviews_updated_at before update on public.reviews for each row execute function public.set_updated_at();

-- Only normal users get a profile row. Restaurant accounts get a restaurant row.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  role_name text;
begin
  role_name := coalesce(new.raw_user_meta_data ->> 'role', 'user');

  if role_name = 'user' then
    insert into public.profiles (auth_user_id, name, username, email, phone_number, city, address)
    values (
      new.id,
      coalesce(new.raw_user_meta_data ->> 'name', ''),
      coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
      new.email,
      new.raw_user_meta_data ->> 'phone_number',
      new.raw_user_meta_data ->> 'city',
      new.raw_user_meta_data ->> 'address'
    )
    on conflict (auth_user_id) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.update_restaurant_rating()
returns trigger language plpgsql as $$
declare target_restaurant_id bigint;
begin
  target_restaurant_id := case when tg_op = 'DELETE' then old.restaurant_id else new.restaurant_id end;
  update public.restaurants
  set rating = coalesce((select round(avg(rating)::numeric, 1) from public.reviews where restaurant_id = target_restaurant_id), 0)
  where id = target_restaurant_id;
  return coalesce(new, old);
end;
$$;

drop trigger if exists reviews_rating_trigger on public.reviews;
create trigger reviews_rating_trigger
after insert or update or delete on public.reviews
for each row execute function public.update_restaurant_rating();

alter table public.profiles enable row level security;
alter table public.restaurants enable row level security;
alter table public.menu_items enable row level security;
alter table public.reservations enable row level security;
alter table public.reviews enable row level security;

-- Clean policies so this script can be re-run.
do $$
declare p record;
begin
  for p in select policyname, tablename from pg_policies where schemaname = 'public'
    and tablename in ('profiles','restaurants','menu_items','reservations','reviews') loop
    execute format('drop policy if exists %I on public.%I', p.policyname, p.tablename);
  end loop;
end $$;

-- Profiles
create policy "profiles_select_public" on public.profiles for select using (true);
create policy "profiles_update_own" on public.profiles for update
using (auth_user_id = auth.uid()) with check (auth_user_id = auth.uid());

-- Restaurants
create policy "restaurants_select_public" on public.restaurants for select using (true);
create policy "restaurants_insert_own" on public.restaurants for insert
with check (auth_user_id = auth.uid());
create policy "restaurants_update_own" on public.restaurants for update
using (auth_user_id = auth.uid()) with check (auth_user_id = auth.uid());

-- Menu
create policy "menu_select_public" on public.menu_items for select using (true);
create policy "menu_insert_owner" on public.menu_items for insert
with check (exists (select 1 from public.restaurants r where r.id = restaurant_id and r.auth_user_id = auth.uid()));
create policy "menu_update_owner" on public.menu_items for update
using (exists (select 1 from public.restaurants r where r.id = restaurant_id and r.auth_user_id = auth.uid()))
with check (exists (select 1 from public.restaurants r where r.id = restaurant_id and r.auth_user_id = auth.uid()));
create policy "menu_delete_owner" on public.menu_items for delete
using (exists (select 1 from public.restaurants r where r.id = restaurant_id and r.auth_user_id = auth.uid()));

-- Reservations
create policy "reservations_select_user_or_restaurant" on public.reservations for select
using (
  exists (select 1 from public.profiles p where p.id = user_id and p.auth_user_id = auth.uid())
  or
  exists (select 1 from public.restaurants r where r.id = restaurant_id and r.auth_user_id = auth.uid())
);
create policy "reservations_insert_user" on public.reservations for insert
with check (exists (select 1 from public.profiles p where p.id = user_id and p.auth_user_id = auth.uid()));
create policy "reservations_update_user_or_restaurant" on public.reservations for update
using (
  exists (select 1 from public.profiles p where p.id = user_id and p.auth_user_id = auth.uid())
  or
  exists (select 1 from public.restaurants r where r.id = restaurant_id and r.auth_user_id = auth.uid())
)
with check (
  exists (select 1 from public.profiles p where p.id = user_id and p.auth_user_id = auth.uid())
  or
  exists (select 1 from public.restaurants r where r.id = restaurant_id and r.auth_user_id = auth.uid())
);

-- Reviews
create policy "reviews_select_public" on public.reviews for select using (true);
create policy "reviews_insert_own" on public.reviews for insert
with check (exists (select 1 from public.profiles p where p.id = user_id and p.auth_user_id = auth.uid()));
create policy "reviews_update_own" on public.reviews for update
using (exists (select 1 from public.profiles p where p.id = user_id and p.auth_user_id = auth.uid()))
with check (exists (select 1 from public.profiles p where p.id = user_id and p.auth_user_id = auth.uid()));
create policy "reviews_delete_own" on public.reviews for delete
using (exists (select 1 from public.profiles p where p.id = user_id and p.auth_user_id = auth.uid()));

-- Helpful view
create or replace view public.restaurant_summary with (security_invoker = true) as
select r.id, r.name, r.email, r.phone_number, r.description, r.address, r.city, r.image_url,
       r.rating, r.created_at,
       count(distinct m.id) as menu_item_count,
       count(distinct rev.id) as review_count
from public.restaurants r
left join public.menu_items m on m.restaurant_id = r.id
left join public.reviews rev on rev.restaurant_id = r.id
group by r.id;

-- IMPORTANT:
-- Supabase Dashboard -> Authentication -> Providers -> Email:
-- For this simple frontend flow, turn OFF "Confirm email" if you want users
-- to login immediately after signup. If it stays ON, users must confirm first.
